#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidFuelUp.Resource", IsApplication=true)]

namespace AndroidFuelUp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int access = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int business_center = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int car_wash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int free_breakfast = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hotel = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int laundry_service = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int local_atm = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int local_parking = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int money = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int photo_camera = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int place = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int restaurant = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int station = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int store = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int wc = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int wifi_black = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int HiButton = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int imageBtnAccess = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int imageBtnBusinessCenter = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int imageBtnCarWash = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int imageBtnHotel = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int imageBtnLocalAtm = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int imageBtnMoney = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int imageBtnStation = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int imageBtnStore = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int imageBtnWc = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int imageBtnWiFi = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ImgBtnAccess = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int ImgBtnBusinesssCenter = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ImgBtnMoney = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int ImgBtnStaition = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
